import React from "react";
import RadioGroup from "@/components/forms/RadioGroup/RadioGroup";
import { DEFAULT_IMAGE_QUALITY } from "@/constants";

interface ImageQualityProps {
  imageQuality?: UserSettings["imageQuality"];
}

const ImageQuality: React.FC<ImageQualityProps> = (props) => {
  const imageQuality = props.imageQuality ?? DEFAULT_IMAGE_QUALITY;

  return (
    <RadioGroup
      title="Image quality"
      name="image-quality"
      radios={[
        {
          id: "imageQualityThumbnail",
          isChecked: imageQuality === "thumbnail",
          label: "Thumbnail",
          value: "thumbnail",
        },
        {
          id: "imageQualityOriginal",
          isChecked: imageQuality === "original",
          label: "Original",
          value: "original",
        },
      ]}
    >
      <small>
        <p className="mt-2">Select the quality of the performer images.</p>
        <p>
          Thumbnails are smaller in size but may need to be generated by Stash
          before they appear on the screen. Original image files don't require
          processing but may take more time to load depending on their size and
          your network speed.
        </p>
      </small>
    </RadioGroup>
  );
};

export default ImageQuality;
